export const auraTokens = {
  colors: {
    surface: '#f7f9fb',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f2f4f6',
    surfaceContainer: '#eceef0',
    surfaceContainerHigh: '#e6e8ea',
    surfaceContainerHighest: '#e0e3e5',
    onSurface: '#191c1e',
    onSurfaceVariant: '#45464d',
    outline: '#76777d',
    outlineVariant: '#c6c6cd',
    primary: '#000000',
    onPrimary: '#ffffff',
    primaryContainer: '#131b2e',
    onPrimaryContainer: '#7c839b',
    secondary: '#006c49',
    onSecondary: '#ffffff',
    secondaryContainer: '#6cf8bb',
    onSecondaryContainer: '#00714d',
    tertiary: '#000000',
    onTertiary: '#ffffff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    background: '#f7f9fb',
    onBackground: '#191c1e',
  },
  typography: {
    fontFamily: 'Inter, Segoe UI, Roboto, sans-serif',
    dataMonoFamily: 'JetBrains Mono, SFMono-Regular, ui-monospace, monospace',
    displayLg: {
      fontSize: '3rem',
      fontWeight: 700,
      lineHeight: 1.16,
      letterSpacing: '-0.02em',
    },
    headlineLg: {
      fontSize: '2rem',
      fontWeight: 600,
      lineHeight: 1.25,
      letterSpacing: '-0.01em',
    },
    headlineLgMobile: {
      fontSize: '1.5rem',
      fontWeight: 600,
      lineHeight: 1.33,
      letterSpacing: '-0.01em',
    },
    titleMd: {
      fontSize: '1.25rem',
      fontWeight: 600,
      lineHeight: 1.4,
      letterSpacing: '0',
    },
    bodyLg: {
      fontSize: '1rem',
      fontWeight: 400,
      lineHeight: 1.5,
      letterSpacing: '0',
    },
    bodySm: {
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: 1.43,
      letterSpacing: '0',
    },
    labelCaps: {
      fontSize: '0.75rem',
      fontWeight: 600,
      lineHeight: 1.33,
      letterSpacing: '0.05em',
    },
    dataMono: {
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: 1.43,
      letterSpacing: '0',
    },
  },
  radius: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  spacing: {
    base: 8,
    containerPaddingMobile: 16,
    containerPaddingDesktop: 32,
    stackSm: 4,
    stackMd: 12,
    stackLg: 24,
  },
  shadows: {
    card: '0px 1px 2px rgba(15, 23, 42, 0.08)',
    elevated: '0px 12px 24px -4px rgba(15, 23, 42, 0.08)',
    topBar: '0px 4px 12px rgba(15, 23, 42, 0.05)',
  },
} as const

export type AuraTokens = typeof auraTokens
